#!/usr/bin/env sh

# Grab all the submodules
cd ~/.dotfiles
git submodule init
git submodule update

# Create symlinks to dotfiles
dotfiles='zshrc gitconfig gitignore gemrc railsrc irbrc pryrc tmux.conf vim vimrc'
for f in $dotfiles; do
  ln -s ~/.dotfiles/$f ~/.$f
done

# Create some temporary directories
mkdir -p ~/.vim/tmp/undo

# Set zsh as the default shell
chsh -s /bin/zsh

# We're done
echo "Start a new terminal and enjoy!"
