#!/usr/bin/env sh

DOTFILES=$(dirname `readlink $0`)

# Install dependencies {{{

echo "Installing dependencies..."

# Submodules
cd $DOTFILES
git submodule --quiet init
git submodule --quiet update

# rbenv
git clone --quiet git://github.com/sstephenson/rbenv.git ~/.rbenv
git clone --quiet git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# }}}

# Create symlinks {{{

echo "Creating symlinks..."

symlinks='zshrc gitconfig gitignore gemrc railsrc irbrc pryrc tmux.conf vim vimrc tm_properties rbenv'
for f in $symlinks; do
    ln -s -f $DOTFILES/$f ~/.$f
done

# Set up some extra files and directories
ln -s -f $DOTFILES/zsh/gnapse.zsh-theme $DOTFILES/oh-my-zsh/custom/
ln -s -f $DOTFILES/zsh/plugins $DOTFILES/oh-my-zsh/custom/
ln -s -f $DOTFILES/tmux/powerlinerc ~/.tmux-powerlinerc

# }}}

# Set zsh as the default shell {{{

if [[ $SHELL != "/bin/zsh" ]]; then
    echo "Setting zsh as the default shell..."
    chsh -s /bin/zsh
fi

# }}}

# We're done
echo "Start a new terminal and enjoy!"
