#!/usr/bin/env sh

DOTFILES=$(dirname $0)

# Install dependencies {{{

echo "Installing dependencies..."

# Submodules
cd $DOTFILES
git submodule --quiet init
git submodule --quiet update

# rbenv
git clone --quiet git://github.com/sstephenson/rbenv.git ~/.rbenv
git clone --quiet git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# fish shell
brew install fish
git clone --quiet git://github.com/bpinto/oh-my-fish.git ~/.oh-my-fish

# }}}

# Create symlinks {{{

echo "Creating symlinks..."

symlinks='gitconfig gitignore gemrc railsrc irbrc pryrc vim vimrc tm_properties rubocop.yml'
for f in $symlinks; do
    ln -s -f $DOTFILES/$f ~/.$f
done

# Set up some extra files and directories
ln -s -f $DOTFILES/tmux/powerlinerc ~/.tmux-powerlinerc
ln -s -f $DOTFILES/oh-my-fish/config.fish ~/.config/fish/config.fish

# Apply special tmux config when in OSX
if [[ "$(uname)" = "Darwin" ]]; then
    ln -s -f $DOTFILES/tmux-osx.conf ~/.tmux.conf
else
    ln -s -f $DOTFILES/tmux.conf ~/.tmux.conf
fi

# }}}

# Set fish as the default shell {{{

if [[ $SHELL != "/usr/local/bin/fish" ]]; then
    echo "Setting fish as the default shell..."
    chsh -s /usr/local/bin/fish
fi

# }}}

# We're done
echo "Start a new terminal and enjoy!"
